### PR TITLE
Improve HTTP example

### PR DESCRIPTION
**Pull request by KuthumiPepple**
@tadayosi @Delawen I provided more context for the examples. The examples run ok. Let me know if any change is needed.

### CODE REVIEW

**Comment by Delawen** [comment]
The change to `https` is because browsers now fallback by default to `https`?

**Comment by KuthumiPepple** [comment]
What change are you referring to?

**Comment by Delawen** [comment]
Oh sorry, I was confused with the improvement on the comments. I thought the jkeystore was something now. Now I see it was there the whole time.

**Comment by Delawen** [comment]
LGTM

**Review by tadayosi — APPROVED** [review]

**Pull request merged**
