### PR TITLE
add context to basic example

### PR DESCRIPTION
**Pull request by KuthumiPepple**
@Delawen @tadayosi I added some context to the readme. Let me know if there is more to be done here.

### CODE REVIEW

**Review by tadayosi — COMMENTED** [review]
Great writing.

Now I wonder if `basic` is the right name for the example directory. Shouldn't we change it to `env`?

I also found that `Env.java` isn't formatted well. Let's take this opportunity to format it prettily as well.

```
  public void configure() throws Exception {
	  from("timer:tick")
        .log("${env:MY_ENV_VAR}");
  }
```

**Comment by KuthumiPepple** [comment]
Thanks for the review. I agree that `env` is a more apt name. I'd do the formatting as well.

**Comment by KuthumiPepple** [comment]
@tadayosi the changes have been done

**Review by tadayosi — APPROVED** [review]
LGTM

**Comment by tadayosi** [comment]
@KuthumiPepple I noticed that the top README.md had a link to old basic example, which is missing now. Can you update the top README as well? Thank you.

**Pull request merged**
